#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCCfHO1sZHAVq2VwPIYq2EbArmYKIfxh6F1kyLW6a6JYWDtSkfcgr39WvQaskJC/UtKTJxvwLZk5cSw2k3q9HbB+FY8IPxgKIorecuVEjNXzO5G/7SkzadyLU+XeCjaLVfD6Nyz9s2aJtpMD5sUn2A34/VPwgE30t/dNE4TwaCfs8K09SafmM3GJZ7U5vou2vLYo3X/hhZDcwMzqR4uj1t4E+Vho0KCMSZN7fztp4EPjkAys1koVo/9+5oGGWVNlkA9m+0+iCp2tl+vJdxgvWUf4PQXaAqB73mH4ll58vu3LtaHtkf8Dl3q+FjvFFE6dD2t9euIZ/eZDs7//LcVXCTB

# Downloads the golang package
packages:
  - golang-go

# Setsthe GOPATH & downloads the demo payload
runcmd:
  - sudo su terraform
  - sudo mkdir /home/terraform/go
  - sudo chown terraform:hashicorp /home/terraform/go
  - export GOPATH=/home/terraform/go
  - go get github.com/hashicorp/learn-go-webapp-demo